### ISSUE TITLE
The variable aren't showed

### ISSUE THREAD

**Issue by RisedSky** [Nekos-life/nekos-dot-life#2]
![image](https://user-images.githubusercontent.com/23197999/44003854-21af6b7c-9e5a-11e8-8517-105806df177a.png)
I have the latest update
![image](https://user-images.githubusercontent.com/23197999/44003869-5e5beeba-9e5a-11e8-830e-90037d4b2073.png)

**Comment by TheCyberRonin** [comment]
That's most likely because they are dynamically created with the JSON file. I suppose by `not showed`, you mean that there is no intellisense associated with the variables? If so, that would most likely be the reason, I can maybe look into adding a typings file or some jsdocs to make intellisense work.

**Comment by TheCyberRonin** [comment]
The new push on GH/npm should have added the support for intellisense :)

**Comment by RisedSky** [comment]
thanks ! :D
